---
title: Falmesino.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Falmesino Abdul Hamid
description: Web Developer from Somewhere
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png
footer-links:
  dribbble: 
  email: falmesino@gmail.com
  facebook: falmesinoh
  flickr: 
  github: falmesino
  instagram: falmesino
  linkedin: 
  pinterest: 
  rss: 
  twitter: falmesino
  stackoverflow: 
  youtube: "/falmesino"
  googleplus: 
disqus: 
google_analytics: 
url: http://falmesino.github.io
baseurl: 
#markdown: redcarpet
highlighter: pygments
permalink: "/:title/"
version: v1.1.0
sass:
  style: expanded
gems:
- jekyll-sitemap
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
